# Generated by Django 4.2.5 on 2024-08-19 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mail", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mailsettings",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="create_mail",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Добавил рассылку",
            ),
        ),
        migrations.AddField(
            model_name="logs",
            name="mail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="get_log",
                to="mail.mailsettings",
                verbose_name="рассылка",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="create_client",
                to=settings.AUTH_USER_MODEL,
                verbose_name="добавил клиента",
            ),
        ),
    ]
