# Generated by Django 4.2.5 on 2024-08-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailsettings",
            name="period",
            field=models.CharField(
                choices=[
                    ("day", "Раз в день"),
                    ("week", "Раз в неделю"),
                    ("month", "Раз в месяц"),
                ],
                default="day",
                max_length=50,
                verbose_name="Периодичность рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailsettings",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("in_process", "Запущена"),
                    ("finished", "Завершена"),
                ],
                default="in_process",
                max_length=50,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
