# Generated by Django 4.2.5 on 2024-08-27 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0003_alter_mailsettings_period_alter_mailsettings_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailsettings",
            name="end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Введите время и дату в формате",
                null=True,
                verbose_name="Время окончания",
            ),
        ),
        migrations.AlterField(
            model_name="mailsettings",
            name="period",
            field=models.CharField(
                choices=[
                    ("day", "Раз в день"),
                    ("week", "Раз в неделю"),
                    ("month", "Раз в месяц"),
                ],
                max_length=50,
                verbose_name="Периодичность рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailsettings",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 27, 22, 35, 53, 605516),
                help_text="Введите время и дату в формате",
                verbose_name="Время начала рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailsettings",
            name="status",
            field=models.CharField(
                choices=[
                    ("create", "Создана"),
                    ("in_process", "Запущена"),
                    ("finished", "Завершена"),
                ],
                default="in_process",
                max_length=50,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
