# Generated by Django 4.2.5 on 2024-08-27 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0004_alter_mailsettings_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailsettings",
            name="end_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время окончания"
            ),
        ),
        migrations.AlterField(
            model_name="mailsettings",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 27, 22, 54, 10, 896666),
                verbose_name="Время начала рассылки",
            ),
        ),
    ]
