# Generated by Django 4.2 on 2024-08-31 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0005_alter_mailsettings_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailsettings",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 31, 19, 32, 48, 991602),
                verbose_name="Время начала рассылки",
            ),
        ),
    ]
